### ISSUE TITLE
LspStopServer => LspStop

### ISSUE THREAD

**Issue by ForceFaction** [sago35/tinygo.vim#2]
I'm not sure if it's specific to neovim, but i had to change LspStopServer to LspStop as the former doesn't exist.

**Comment by sago35** [comment]
@ForceFaction 

I don't use nvim, but I created a PR to try it out.
Can you check to see if it works correctly?

**Comment by ForceFaction** [comment]
Yes, this works for me. Thanks for having a look at it :)
